#!/bin/sh

# TODO: 󰗊: Language Switcher
# Start essential programs
sxhkd &

# Set Atom One Dark-like colors for bspwm
# Base colors
FOREGROUND="#ABB2BF"
BACKGROUND="#282C34"
BLACK="#282C34"
RED="#E06C75"
GREEN="#98C379"
YELLOW="#E5C07B"
BLUE="#61AFEF"
MAGENTA="#C678DD"
CYAN="#56B6C2"
WHITE="#ABB2BF"

# Set bspwm colors
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$BLUE"
bspc config focused_border_color "$BLUE"
bspc config presel_feedback_color "$GREEN"

# Apply default theme (dark)
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Nordic'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'

# Start picom compositor
picom &

# Start Notifications Dunst
dunst &

# Set wallpaper
feh --bg-fill --randomize ~/Pictures/wallpaper/* &

# Kill existing polybar instances
killall -q polybar
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch polybar
nm-applet &
polybar main &

# Start greenclip if not already running
pgrep -x greenclip || greenclip daemon &

# Monitor settings
bspc monitor -d   󰬡  󰍩  󰽰    

# Global settings
bspc config border_width         4
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Window rules
#
# App Rules
bspc rule -a firefox desktop='^2'
bspc rule -a Zotero desktop='^3'
bspc rule -a obsidian desktop='^4'
bspc rule -a Slack desktop='^6'
bspc rule -a Signal desktop='^5'
bspc rule -a obs desktop='^8'

# Custom Rules
bspc rule -a yazi state=floating center=true
bspc rule -a markdown_cheatsheet state=floating sticky=on center=true rectangle=800x600+0+0
bspc rule -a Pavucontrol state=floating center=true

# Autostart applications (all except OBS)
firefox &
zotero &
obsidian &
slack &
# signal-desktop &
# ncspot &
# obs &

# Start Ghostty terminal on desktop 9 pointing to /etc/nixos
# ghostty --class nixos --working-directory /etc/nixos &

# Switch to desktop 9 after starting Ghostty
